# Generated by Django 3.1.4 on 2021-03-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_fullwidth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarLeft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField(max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SidebarRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField(max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
    ]
