# Generated by Django 3.1.4 on 2021-03-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210329_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uchlik',
            old_name='description_uz',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='uchlik',
            old_name='name_uz',
            new_name='name',
        ),
    ]
